export const BRANDS = {
	ARBYS: "arbys",
	AUNTY_ANNES: "aunty-annes",
	BETOS: "betos",
	BLACK_BEAR_DINER: "black-bear-diner",
	CHICK_FIL_A: "chick-fil-a",
	CHILIS: "chilis",
	COSTA_VIDA: "costa-vida",
	COSTCO: "costco",
	DAIRY_QUEEN: "dairy-queen",
	DEL_TACO: "del-taco",
	DOMINOS: "dominos",
	JIMS: "jims",
	LITTLE_CAESARS: "little-caesars",
	LOS_HERMANOS: "los-hermanos",
	MARCOS: "marcos",
	MCDONALDS: "mcdonalds",
	OLIVE_GARDEN: "olive-garden",
	PAPA_JOHNS: "papa-johns",
	PAPA_MURPHYS: "papa-murphys",
	PIZZA_HUT: "pizza-hut",
	PIZZA_PIE_CAFE: "pizza-pie-cafe",
	RAISING_CANES: "raising-canes",
	RED_BARON: "red-baron",
	RED_ROBIN: "red-robin",
	SEVEN_ELEVEN: "7-eleven",
	SONIC: "sonic",
	TACO_AMIGO: "taco-amigo",
	TACO_BELL: "taco-bell",
	TEXAS_ROADHOUSE: "texas-roadhouse",
	TOSTINOS: "tostinos",
	WAFFLE_LOVE: "waffle-love",
	WENDYS: "wendys",
} as const;

export type Brand = (typeof BRANDS)[keyof typeof BRANDS];
