import { CATEGORIES } from "../categories";

import type { Food } from "../types";

export const DESSERT_FOODS: Food[] = [
	{
		category_key: CATEGORIES.dessert,
		id: 1,
		image_url: "/graphics/sweets/dessert/glazed-donut.jpg",
		name: "Donut",
		slug: "donut",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 72,
		image_url: "/graphics/sweets/dessert/apple-pie.jpg",
		name: "Apple Pie",
		slug: "apple-pie",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 73,
		image_url: "/graphics/sweets/dessert/brownies.jpg",
		name: "Brownies",
		slug: "brownies",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 74,
		image_url: "/graphics/sweets/dessert/chocolate-pie.jpg",
		name: "Chocolate Pie",
		slug: "chocolate-pie",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 75,
		image_url: "/graphics/sweets/dessert/cinnamon-roll.jpg",
		name: "Cinnamon Roll",
		slug: "cinnamon-roll",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 76,
		image_url: "/graphics/sweets/dessert/cookie.jpg",
		name: "Cookie",
		slug: "cookie",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 77,
		image_url: "/graphics/sweets/dessert/cookie-dough.jpg",
		name: "Cookie Dough",
		slug: "cookie-dough",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 78,
		image_url: "/graphics/sweets/dessert/cookie-dough-pizza.jpg",
		name: "Cookie Dough Pizza",
		slug: "cookie-dough-pizza",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 79,
		image_url: "/graphics/sweets/dessert/cupcake.jpg",
		name: "Cupcake",
		slug: "cupcake",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 80,
		image_url: "/graphics/sweets/dessert/frosty.jpg",
		name: "Frosty",
		slug: "frosty",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 81,
		image_url: "/graphics/sweets/dessert/fruit-pizza.jpg",
		name: "Fruit Pizza",
		slug: "fruit-pizza",
		toppings: [
			"Bananas",
			"Black Berries",
			"Blue Berries",
			"Mandarine Oranges",
			"Kiwis",
			"Rasperries",
			"Strawberries",
		],
	},
	{
		category_key: CATEGORIES.dessert,
		id: 82,
		image_url: "/graphics/sweets/dessert/ice-cream.jpg",
		name: "Ice Cream",
		slug: "ice-cream",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 83,
		image_url: "/graphics/sweets/dessert/mint-brownies.jpg",
		name: "Mint Brownies",
		slug: "mint-brownies",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 84,
		image_url: "/graphics/sweets/dessert/peach-cobbler.jpg",
		name: "Peach Cobbler",
		slug: "peach-cobbler",
	},
	{
		category_key: CATEGORIES.dessert,
		id: 85,
		image_url: "/graphics/sweets/dessert/peanut-butter-bars.jpg",
		name: "Peanut Butter Bars",
		slug: "peanut-butter-bars",
	},
];
