import type { Food } from "./types"

export const FOODS: Food[] = [
  {
    id: 1,
    name: "Donut",
    category_key: "sugar_fat_salt",
    category_label: "Sugar, Fat & Salt",
    background_url: "/backgrounds/1-red.png",
    icon_url: "/icons/fruit.png",
    image_url: "/image/sugar-fat-salt/glazed-donut.jpg",
  },
  {
    id: 2,
    name: "Texas Toast",
    category_key: "fats_oils",
    category_label: "Fats & Oils",
    background_url: "/backgrounds/2-yellow.png",
    icon_url: "/icons/fruit.png",
    image_url: "/image/fats-oils/texas-toast.jpg",
    info: "Preheat oven to 425°",
  },
  {
    id: 3,
    name: "Peanut Butter",
    category_key: "protein",
    category_label: "Protein",
    background_url: "/backgrounds/3-orange.png",
    icon_url: "/icons/fruit.png",
    image_url: "/image/protien/peanut-butter.jpg",
  },
  {
    id: 4,
    name: "Milk",
    category_key: "dairy",
    category_label: "Dairy",
    background_url: "/backgrounds/4-blue.png",
    icon_url: "/icons/dairy.png",
    image_url: "/image/dairy/milk.jpg",
  },
  {
    id: 7,
    name: "Babybel Cheese",
    category_key: "dairy",
    category_label: "Dairy",
    background_url: "/backgrounds/4-blue.png",
    icon_url: "/icons/dairy.png",
    image_url: "/image/dairy/babybel-cheese.jpg",
  },
  {
    id: 8,
    name: "Chocolate Milk",
    category_key: "dairy",
    category_label: "Dairy",
    background_url: "/backgrounds/4-blue.png",
    icon_url: "/icons/dairy.png",
    image_url: "/image/dairy/chocolate-milk.jpg",
  },
  {
    id: 5,
    name: "Mashed Potatoes",
    category_key: "grains",
    category_label: "Grains",
    background_url: "/backgrounds/5-purple.png",
    icon_url: "/icons/fruit.png",
    image_url: "/image/grains/mashed-potatoes.jpg",
  },
  {
    id: 6,
    name: "Grapes",
    category_key: "fruit_veg",
    category_label: "Fruit & Vegetables",
    background_url: "/backgrounds/6-green.png",
    icon_url: "/icons/fruit.png",
    image_url: "/image/fruit-and-vegi/grapes.jpg",
  },
]
